<!DOCTYPE html> 
 <html xmlns="http://www.w3.org/1999/xhtml" xmlns:v="urn:schemas-microsoft-com:vml" xmlns:o="urn:schemas-microsoft-com:office:office"><head><title>LIFT015 Operation Next Email #3 - Generic</title>
    <meta http-equiv="Content-Type" content="text/html" charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
  	<meta name="color-scheme" content="light dark">
	<meta name="supported-color-schemes" content="light dark">
	<link rel="preconnect" href="https://fonts.googleapis.com">
	<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin="">
	<link href="https://fonts.googleapis.com/css2?family=Oswald:wght@300;400;500;600;700&amp;family=Roboto&amp;family=Roboto+Slab:wght@700&amp;display=swap" rel="stylesheet">
    <style sh-template-styles="">/* Generated CSS, do not edit */
.rss-widget a.rss-title {
  color: rgb(91, 156, 199);
}
.rss-widget, .rss-widget a {
  color: rgb(91, 156, 199);
}
</style>
    <style sh-font-styles="">
      /* Generated by SharpSpring -- Do not edit */
      * {-webkit-text-size-adjust: none}
      [class].font1 {font-family: 'Roboto',Arial, sans-serif !important;}
      [class].font2 {font-family: 'Roboto',Arial, sans-serif !important;}
      table tr th { text-align: left; border-spacing: 0;  }
      .rounder { max-height: 149px; }
      .rightBorder { border-right:1px solid #4F7E90; }
      .preHeader { display: none; }
      .hideDesktop { display: none; }
      .gutterCol { width: 17.5%;}
      .mainCol { width: 65%; }
    </style>
    <style>
      @media screen and (max-width: 600px) {
		  .mobileBox1 { text-align: center!important; border: none !important; padding: 20px !important;}
		.centerMobileIMG { margin:0 auto; }
      .scaleImg1 { width: 150px !important; }
      .scaleFont1, .scaleFont2, .scaleFont3 { font-size:130% !important; line-height: 130% !important }
      .hideDesktop { display: block !important; }
      .hideMobile { display:none !important; }
      .rounder { max-height: unset !important; }
      .rightBorder { border: 0 !important; }
      table.full, table.fullCenter, tr:not(.noCollapse), table {
      width:100% !important;
      max-width:100% !important;
      border-spacing:0 !important;
      }
      table.keepWidth, table.moneyBoxes {  width: auto !important; margin:0 auto !important; }
      tr.collapse-mobile:not(.noCollapse) td {
      width:100% !important;
      display:block;
      padding:0 0 10px 0 !important;
      }
		  .singleCollapse {
      width:100% !important;
      display:block;
      padding:0 0 10px 0 !important;
      }
      tr.collapse-mobile td.btnCenter table { width: auto !important; margin:0 auto !important;}
      tr.collapse-mobile td.buttonTable {
      width:fit-content !important;
      margin: 0 auto;
      }
      table.keepWidth tr th {
      padding: 0 !important;	
      width: auto !important;
      }
      tr.collapse-mobile.mobileCentered td {
      text-align: center !important;
      }
      tr.collapse-mobile {
      display:block !important;
      }
      a {
      text-decoration:none !important;
      }
      .fwMobile {
      width:100% !important;
      height:auto !important;
      }
      .centerMobile {
      text-align:center !important;
      }
      .text {
      padding: 0 20px !important;
      }
      .spaceItBetter {
      padding: 0 20px !important;
      }
		  .betterCheck { margin:2px 0  !important}
		  .hunderdPercent { width: 100% !important;}
		  .betterUL { padding: 0px 40px 0 40px !important;}
		  .mobileMargins { margin:0 0 10px !important;}
		  .socialsFooter { width:auto !important;}
		  .phoneEmailTable { width: auto !important;}
		  .noBorderMobile { border: none !important;}
		  .phoneEmailTable td { width: auto; }
		  
		  #noPaddingMobile { padding: 0 !important;}
		  
		.jobListTable tr td#jobBullet { width: 9px !important;}
		.jobListTable tr td#jobContent { width: auto !important;  }
		.jobListTable tr td#jobBullet,
		.jobListTable tr td#jobContent {  display: table-cell !important; }
      }
    </style>
    <style>
      @media screen and (max-width: 420px) {
		  
		  .betterCheck { margin:4px 0  !important}
      .scaleFont1, .scaleFont2, .scaleFont3 {
      font-size:100% !important;
      line-height: 100% !important;
      }
      .scaleImg1 {
      width: 100px !important;
      }
      }
    </style>
	<style>
	  @media (prefers-color-scheme: dark ) {
		.dark-logo-wrapper,.dark-logo {
			display: block !important;
		}
		.light-logo {
			display: none !important;
		}
	  }
	</style>
  </head>
  <body class="body show-dynamic" style="font-family: Helvetica; color: rgb(35, 31, 32); margin: 0px; background-color: rgb(255, 255, 255);" bgcolor="#ffffff" data-new-gr-c-s-check-loaded="14.1157.0" data-gr-ext-installed=""><span class="preHeader" style="color:#fff; display: none;">PREHEADER HERE</span><table border="0" cellpadding="0" cellspacing="0" align="center" class="full body" style="background-color: rgb(255, 255, 255); margin-top:0px;" bgcolor="#ffffff">
          <tbody>
            <tr>
			<th width="29" class="hideMobile">&nbsp;</th>
              <th width="542" align="center" valign="top" class="">
	  
	  
        <table border="0" cellpadding="0" cellspacing="0" align="center" class="full body headerTop" style="color: rgb(35, 31, 32); background-color: rgb(255, 255, 255);" bgcolor="#ffffff">
          <tbody>
            <tr>
              <th align="center" valign="top" class="">
                <table sh-layout-editable="" sh-theme-bg="true" width="542" border="0" cellpadding="0" cellspacing="0" align="center" class="full content" bgcolor="#ffffff" style="width: 542px; background-color: rgb(255, 255, 255);">
                  <tbody>
                    <tr>
                      <th align="center">
                        <table class="mobile" align="center" border="0" width="100%" cellpadding="0" cellspacing="0" style="width: 542px;">
                          <tbody>
                            <tr>
                              <th align="center">
                                <table width="542" border="0" cellpadding="0" cellspacing="0" align="center" class="full" style="width: 542px;">
                                  <tbody>
                                    <tr>
                                      <th width="100%" align="center" class="">
                                        <table width="542" border="0" cellpadding="0" cellspacing="0" align="center" style="border-collapse: collapse; mso-table-lspace: 0pt; mso-table-rspace: 0pt; width: 542px;" class="fullCenter">
                                          <tbody>
                                            <tr>
                                              <th align="center">
                                                <table style="border-collapse: collapse; mso-table-lspace: 0pt; mso-table-rspace: 0pt;" border="0" width="100%" cellspacing="0" cellpadding="0" class="">
                                                  <tbody>
                                                    <tr>
                                                      <td bgcolor="#fff" width="542" valign="top" style="">
                                                        <div>
                                                          <table border="0" align="left" cellpadding="0" cellspacing="0" background="#FFFFFF" style="background: #FFFFFF; margin:0;border-collapse: collapse; mso-table-lspace: 0pt; mso-table-rspace: 0pt;" class="">
                                                            <tbody>
                                                              <tr class="">
                                                                <td height="11" colspan="3" class=""></td>
                                                              </tr>
                                                              <tr class="collapse-mobile">
<td width="116" class="">
	<img src="https://ss-usa.s3.amazonaws.com/companies/MzQ0MAIA/uploads/634dbef259a43/logo.png" width="116" height="53" alt="OPERATION NEXT" style="display:block;max-width:100%;height:auto;" class="centerMobileIMG ">
</td>
																  
		  
																  
<td width="108" class="">
	<img src="https://ss-usa.s3.amazonaws.com/companies/MzQ0MAIA/uploads/634dbef259a43/poweredby.png" width="108" height="21" alt="OPERATION NEXT" style="display:block;max-width:100%;height:auto;" class="centerMobileIMG ">
</td>
													
																  
<td valign="middle" width="189" style="padding: 5px 10px 5px 0px; border-right: 1px solid #273c8c; text-align: right" class="hideMobile centerMobile noBorderMobile">
<a href="https://www.opnextjobs.com/enroll/" target="_blank" style="font-family: 'Roboto Slab', serif; font-weight: 700; text-decoration: none; color: #273c8c; font-size:11px;">OPNEXTJOBS.com/Enroll</a></td>

<td valign="middle" width="108" style="padding: 6px 0 6px 10px;" class="hideMobile centerMobile">
<p style=" margin: 0;font-family: 'Roboto Slab', serif; font-weight: 700; text-decoration: none; color: #273c8c; font-size:11px; line-height: 11px;">Call or Text Today</p>
<a href="tel:(313) 355-2478" target="_blank" style="font-family: 'Roboto Slab', serif; font-weight: 700; text-decoration: none; color: #273c8c; font-size:11px; line-height: 11px;">(313) 355-2478</a>
</td>
                                                                
                                                                
                                                               
                                                              </tr>
																   <tr class="collapse-mobile">
                                                                <td height="14" width="542" style="border-bottom: 2px solid #273c8c;" colspan="6" class="hideMobile"></td>
                                                                
                                                                
                                                               
                                                              </tr>
															
									  <!--[if !mso]><! -->
													<tr class="hideDesktop">											<td>
														
														
<table width="100%" align="center" border="0" cellpadding="0" cellspacing="0" background="#FFFFFF" style="width:100%; background: #FFFFFF; margin:0 auto;border-collapse: collapse; mso-table-lspace: 0pt; mso-table-rspace: 0pt;" class="">
                                                            <tbody>	
																<tr>
<td valign="middle" width="50%" style=" width: 50vw; text-align: right; padding: 3px 15px 3px 3px;border-right: 1px solid #273c8c;">
<a href="https://www.opnextjobs.com/enroll/" target="_blank" style="font-family: 'Roboto Slab', serif; font-weight: 700; text-decoration: none; color: #273c8c;   font-size:12px;">OPNEXTJOBS.com/Enroll</a></td>
																	

<td valign="middle" width="50%" style=" width: 50vw;padding:3px 3px 3px 15px" class="">
<a href="https://www.opnextjobs.com/enroll/" target="_blank" style="font-family: 'Roboto Slab', serif; font-weight: 700; text-decoration: none; color: #273c8c; font-size:12px; line-height: 11px;">CALL: (757) 638-7018</a>
																</td></tr>
															  </tbody>
															</table>
                       </td>						                                         
                                                                
                                                               
                                                              </tr>
																	<!--<![endif]-->
																<tr class="hideDesktop">											<td height="10"></td></tr>
                                                            </tbody>
                                                          </table>
                                                        </div>
                                                      </td>
                                                    </tr>
                                                  </tbody>
                                                </table>
                                              </th>
                                            </tr>
                                          </tbody>
                                        </table>
                                      </th>
                                    </tr>
                                  </tbody>
                                </table>
                              </th>
                            </tr>
                          </tbody>
                        </table>
                      </th>
                    </tr>
                  </tbody>
                </table>
              </th>
            </tr>
          </tbody>
        </table>
        <table border="0" cellpadding="0" cellspacing="0" align="center" class="full body" style="color: rgb(35, 31, 32); background-color: rgb(255, 255, 255);" bgcolor="#FFF">
          <tbody>
            <tr>
              <th align="center" valign="top">
                <table sh-layout-editable="" sh-theme-bg="true" width="542" border="0" cellpadding="0" cellspacing="0" align="center" class="full content" bgcolor="#ffffff" style="width: 542px; background-color: rgb(255, 255, 255);">
                  <tbody>
                    <tr>
                      <th width="100%" border="0" cellpadding="0" cellspacing="0" align="center">
                        <table class="mobile" align="center" border="0" width="100%" cellpadding="0" cellspacing="0">
                          <tbody>
                            <tr>
                              <th width="542" height="10" class="hideMobile"></th>
                            </tr>
                            <tr>
                              <th align="left">
                                <table width="542" border="0" cellpadding="0" cellspacing="0" align="center" bgcolor="#ffffff" style="width: 542px;">
                                  <tbody>
                                    <tr class="hideMobile">
                                     <th width="542" valign="top" align="center" class="">
										<a href="https://www.opnextjobs.com/enroll/" target="_blank"><img src="https://ss-usa.s3.amazonaws.com/companies/MzQ0MAIA/uploads/634dbef259a43/header.png" width="542" height="341" alt="Let Operation Next train you for a high-paying job." style="display:block;max-width:100%;height:auto;" class="centerMobileIMG"></a>
                                        
										  
                                      </th>
                                    </tr>
									  <!--[if !mso]><! -->
									  <tr class="collapse-mobile hideDesktop">
                                     <th width="542" valign="top" align="center" class="hunderdPercent">
										<a href="https://www.opnextjobs.com/enroll/" target="_blank"><img src="https://ss-usa.s3.amazonaws.com/companies/MzQ0MAIA/uploads/634dbef259a43/header-mobile.png" width="600" height="506" alt="Power-up your new career with OPERATION NEXT" style="display:block;max-width:100%;height:auto;" class="centerMobileIMG"></a>
                                        
										  
                                      </th>
                                    </tr>
									  <!--<![endif]-->
                                  </tbody>
                                </table>
								 <table width="542" border="0" cellpadding="0" cellspacing="0" align="center" style="width: 542px; border-collapse: collapse; mso-table-lspace: 0pt; mso-table-rspace: 0pt;">
                                                  <tbody>
													  
                                            <tr><td>
				  
				  
				  <table border="0" cellpadding="0" cellspacing="0" align="center" style="border-collapse: collapse; mso-table-lspace: 0pt; mso-table-rspace: 0pt;">
                                                  <tbody>
													  
                                            <tr>
                                              <th colspan="3" height="25" class=""></th>
                                            </tr>
                                                    <tr valign="top" class="">
														
                                                      <td width="40" class="hideMobile"></td>
                                                     
                                                      <td width="462">
														
<p style="font-size: 14px; color: #000; line-height: 1.3; font-weight: 400; font-family: 'Roboto', Arial, sans-serif; margin: 0 0 15px; text-align: left;" class="spaceItBetter centerMobile">Rejoining the private sector gets a lot easier when you have a good job with 
a clear career path. That’s why so many service members are signing up for 
	training from Operation Next.</p>
<p style="font-size: 14px; color: #000; line-height: 1.3; font-weight: 400; font-family: 'Roboto', Arial, sans-serif; margin: 0; text-align: left;" class="spaceItBetter centerMobile">In as little as three months, you can learn the skills you need to land a 
high-paying role with a top industrial firm. Here’s just one example of the 
many in-demand careers…</p></td>

                                                      
                                                      <td width="41" class="hideMobile"></td>
                                                    </tr>
													  
													 
                                                    
                                                    
                                                  </tbody>
                                                </table>
				  
				  
				  
												</td>
													  </tr>
		  </tbody>
				  </table>
                              </th>
                            </tr> 
							   <tr>
                                              <th height="27" colspan="5" class="hideMobile"> </th>
                                            </tr>  
                            <tr>
                              <th align="left">
                                <table width="542" border="0" cellspacing="0" cellpadding="0" style="border: 1px solid #c5c5bd;" class="noBorderMobile">
                                  <tbody>
                                    <tr>                                                     
                                      <th width="540" class="">
                                        <table border="0" cellspacing="0" cellpadding="0">
                                          <tbody>
                                         
                                            
                                            
											  
											    <tr>
                                              <th height="16"></th>
                                            </tr>
                                            
                                            
											  
											  
											   <tr>
                                              <th>
                                                <table width="540" border="0" cellpadding="0" cellspacing="0" align="center" style="width: 540px;">
                                                  <tbody>
                                                    <tr valign="top">
												  	<td width="16" class="hideMobile"> </td>
													
												  	
													<td width="510">
                                                <table width="510" border="0" cellpadding="0" cellspacing="0" align="center" background="#edecea" style="width: 510px; background-color: #edecea">
													<tbody>
                                            <tr>
                                              <th height="20" colspan="3"></th>
                                            </tr>
                                                    <tr valign="top" class="collapse-mobile">
												  	<td width="13" class="hideMobile"> </td>
												  	<td width="486">
<p style="font-size: 15px; color: #c7312e; line-height: 18px; font-weight: 700; font-family: 'Roboto', sans-serif; margin: 0 0 5px; text-align: left;" class="spaceItBetter">CAREER SPOTLIGHT:</p>

<p style="font-size:28px; color: #273c8c; line-height:30px; font-weight: 700; font-family: 'Roboto', sans-serif; margin: 0 0 7px; text-align: left;" class="spaceItBetter">Welding</p>
														
<p style="font-size: 14px; color: #000000; line-height: 20px; font-weight: 700; font-family: 'Roboto', sans-serif; padding: 0 5px; margin:0; text-align: left;" class="spaceItBetter">
48,800 welding job openings are projected annually nationwide through 
2028. Welders can make up to $63,000 a year. </p>
														
														</td>
												  	<td width="11" class="hideMobile"> </td>
													</tr>
                                            <tr>
                                              <th height="23" class="hideMobile"></th>
                                            </tr>
														
                                                  </tbody>
                                                </table>
													
													</td>
                                                      
													<td width="14" class="hideMobile"> </td>
                                                     
                                                    </tr>
													  
													  
													  
													  
													  
													  <tr valign="top">
												  	<td width="16" class="hideMobile"> </td>
													
												  	
													<td width="510">
                                                <table width="510" border="0" cellpadding="0" cellspacing="0" align="center" background="#edecea" style="width: 510px; background-color: #edecea">
													<tbody>
                                                    <tr valign="top" class="collapse-mobile">
												  	<td width="18" class="hideMobile"> </td>
												  	<td width="265">
														
<p style="font-size: 14px; color: #000000; line-height: 20px; font-weight: 700; font-family: 'Roboto', sans-serif; margin: 0; text-align: left;" class="spaceItBetter">JOB SKILLS</p>

<table width="265" border="0" cellpadding="0" cellspacing="0" align="center" background="#edecea" style="width: 265px; background-color: #edecea" class="jobListTable spaceItBetter">
<tbody>
	<tr class="stopCol">
<td id="jobBullet" width="9" height="16" valign="top">
<!--[if mso]>
<div style="margin-top:3px;">
<![endif]-->
	<img src="https://ss-usa.s3.amazonaws.com/companies/MzQ0MAIA/uploads/634dbef259a43/dot.png" width="9" height="16" alt="bullet" style="display:block;max-width:100%;height:auto;" class="centerMobileIMG">
<!--[if mso]>
</div>
<![endif]-->
</td>
<td width="254" id="jobContent">

<p style="font-size: 14px; color: #000000; line-height: 20px; font-weight: 400; font-family: 'Roboto', sans-serif; margin: 0 0 10px; text-align: left;">Learn how to use hand-welding or 
flame-cutting equipment to assemble 
metal structures and equipment.</p>
	</td>
	</tr>
		<tr>
<td id="jobBullet" width="9" height="16" valign="top">
<!--[if mso]>
<div style="margin-top:3px;">
<![endif]-->
	<img src="https://ss-usa.s3.amazonaws.com/companies/MzQ0MAIA/uploads/634dbef259a43/dot.png" width="9" height="16" alt="bullet" style="display:block;max-width:100%;height:auto;" class="centerMobileIMG">
<!--[if mso]>
</div>
<![endif]-->
</td>
<td width="254">

<p style="font-size: 14px; color: #000000; line-height: 20px; font-weight: 400; font-family: 'Roboto', sans-serif; margin: 0 0 10px; text-align: left;">Use cutters, shapers and measuring 
tools to permanently join parts, fill holes, 
indentations or seams.</p>
	</td>
	</tr>
		<tr>
<td id="jobBullet" width="9" height="16" valign="top">
<!--[if mso]>
<div style="margin-top:3px;">
<![endif]-->
	<img src="https://ss-usa.s3.amazonaws.com/companies/MzQ0MAIA/uploads/634dbef259a43/dot.png" width="9" height="16" alt="bullet" style="display:block;max-width:100%;height:auto;" class="centerMobileIMG">
<!--[if mso]>
</div>
<![endif]-->
</td>
<td width="254">

<p style="font-size: 14px; color: #000000; line-height: 20px; font-weight: 400; font-family: 'Roboto', sans-serif; margin: 0 0 10px; text-align: left;">Inspect materials and structure for 
quality of welds.</p>
	</td>
	</tr>
		<tr>
<td id="jobBullet" width="9" height="16" valign="top">
<!--[if mso]>
<div style="margin-top:3px;">
<![endif]-->
	<img src="https://ss-usa.s3.amazonaws.com/companies/MzQ0MAIA/uploads/634dbef259a43/dot.png" width="9" height="16" alt="bullet" style="display:block;max-width:100%;height:auto;" class="centerMobileIMG">
<!--[if mso]>
</div>
<![endif]-->
</td>
<td width="254">

<p style="font-size: 14px; color: #000000; line-height: 20px; font-weight: 400; font-family: 'Roboto', sans-serif; margin: 0; text-align: left;">Skills include understanding blueprints, 
metallurgy, some specialized math 
like trigonometry, and some basic 
engineering.</p>
	</td>
	</tr>
	</tbody>
														</table>
	

														</td>
														
														
												  	<td width="15" class="hideMobile"> </td>														
												  	<td width="201" id="noPaddingMobile">
														
<table width="201" border="0" cellpadding="0" cellspacing="0" align="center" style="width: 201px;"><tbody>
	<tr><td>
														
														<table width="201" border="0" cellpadding="0" cellspacing="0" align="center" background="#c7312e" style="width: 201px; background-color: #c7312e"><tbody>
															  
															  
                                            <tr>
                                              <th height="13" colspan="5"></th>
                                            </tr>
                                                    <tr valign="middle">
														
														
												  	<td width="20" class="hideMobile"> </td>	
														
														
														
												  	<td width="32">
														
														
														<img src="https://ss-usa.s3.amazonaws.com/companies/MzQ0MAIA/uploads/634dbef259a43/icon-industry.png" width="32" height="28" alt="Industry" style="display:block;max-width:100%;height:auto;" class="centerMobileIMG">
														
														
														</td>	
												  	<td width="10"> </td>
														
												  	<td width="129"><p style="font-size: 14px; color: #FFFFFF; line-height: 20px; font-weight: 700; font-family: 'Roboto', sans-serif; margin: 0; text-align: left; " class="centerMobile">CAREER PATH</p></td>
												  	<td width="10" class="hideMobile"> </td>
														
															  </tr>
															  
															  	  
                                            <tr>
                                              <th height="8" colspan="5" class="hideMobile"></th>
                                            </tr>  
															      <tr valign="middle">
														
														
												  	<td width="20" class="hideMobile"> </td>	
														
														
														
												  	<td width="171" colspan="3">
														<p style="font-size: 14px; color: #FFFFFF; line-height: 20px; font-weight: 400; font-family: 'Roboto', sans-serif; margin: 0; text-align: left;" class="centerMobile spaceItBetter">Marine, automotive, 
petrochemical, aviation, and 
construction firms, among 
many others, need welltrained welders across a 
variety of departments.</p>
														
														
														</td>	
												  	
												  	<td width="10"> </td>
														
															  </tr>
															  
															  			  	  
                                            <tr>
                                              <th height="13" colspan="5" class="hideMobile"></th>
                                            </tr> 
															  
															  </tbody></table>
		
		
		</td></tr>
	
				  			  	  
                                            <tr>
                                              <th height="10" colspan="5"></th>
                                            </tr> 
	<tr><td id="noPaddingMobile">
														
														<table width="201" border="0" cellpadding="0" cellspacing="0" align="center" background="#c7312e" style="width: 201px; background-color: #c7312e"><tbody>
															  
															  
                                            <tr>
                                              <th height="8" colspan="5"></th>
                                            </tr>
                                                    <tr valign="middle">
														
														
												  	<td width="20"> </td>	
														
														
														
												  	<td width="37">
														
														
														<img src="https://ss-usa.s3.amazonaws.com/companies/MzQ0MAIA/uploads/634dbef259a43/icon-salary.png" width="37" height="37" alt="Salary" style="display:block;max-width:100%;height:auto;" class="centerMobileIMG">
														
														
														</td>	
												  	<td width="10" class="hideMobile"> </td>
														
												  	<td width="124"><p style="font-size: 14px; color: #FFFFFF; line-height: 20px; font-weight: 700; font-family: 'Roboto', sans-serif; margin: 0; text-align: left; " class="centerMobile">SALARY</p></td>
												  	<td width="10" class="hideMobile"> </td>
														
															  </tr>
															  
															  	  
                                            <tr>
                                              <th height="4" colspan="5"></th>
                                            </tr>  
															      <tr valign="middle">
														
														
												  	<td width="20" class="hideMobile"> </td>	
														
														
														
												  	<td width="171" colspan="3">
														<p style="font-size: 14px; color: #FFFFFF; line-height: 20px; font-weight: 400; font-family: 'Roboto', sans-serif; margin: 0 0 5px; text-align: left; " class="centerMobile spaceItBetter">Average annual salary 
in US:</p><p style="font-size: 18px; color: #FFFFFF; line-height: 20px; font-weight: 400; font-family: 'Roboto', sans-serif; margin: 0; text-align: left; " class="centerMobile spaceItBetter">$43,910</p>
														
														
														</td>	
												  	
												  	<td width="10" class="hideMobile"> </td>
														
															  </tr>
															  
															  			  	  
                                            <tr>
                                              <th height="10" colspan="5"></th>
                                            </tr> 
															
															
															
															  
															  </tbody></table>
		
		
		</td></tr>
	
	
	
	</tbody></table>
														
														
														</td>
												  	<td width="11" class="hideMobile"> </td>
													</tr>
														
														
                                            <tr>
                                              <th height="20" class="hideMobile"></th>
                                            </tr>
														
                                                  </tbody>
                                                </table>
													
													</td>
                                                      
													<td width="14" class="hideMobile"> </td>
                                                     
                                                    </tr>
													  
													  
													  
                                                  </tbody>
                                                </table>
                                              </th>
											  </tr>
											  
											  
                                            <tr>
                                              <th height="25"></th>
                                            </tr>
											  
											  <tr>
                                              <th>
                                                <table width="540" border="0" cellpadding="0" cellspacing="0" align="center" style="width: 540px;">
                                                  <tbody>
                                                    <tr valign="top">
														
														<td width="20"></td>
                                                      <td width="500"> 														
<p style="text-align: center; margin: 0;"><img src="https://ss-usa.s3.amazonaws.com/companies/MzQ0MAIA/uploads/634dbef259a43/missionaccomplished.png" width="500" height="90" alt="Mission Accomplished!" style="display:block;max-width:100%;height:auto; margin: 0 auto;" class=""></p></td>
                                                      
                                                      
														<td width="20"></td>
                                                     
                                                    </tr>
                                                  </tbody>
                                                </table>
                                              </th>
                                            </tr>
											  
											  
                                            <tr>
                                              <th height="13" class="hideMobile"></th>
                                            </tr>
											  <tr>
                                              <th>
                                                <table width="540" border="0" cellpadding="0" cellspacing="0" align="center" style="width: 540px;">
                                                  <tbody>
                                                    <tr valign="top">
												  	<td width="20"> </td>
													<td width="18"><img src="https://ss-usa.s3.amazonaws.com/companies/MzQ0MAIA/uploads/634dbef259a43/checkmark.png" width="18" height="18" alt="" style="display:block;max-width:100%;height:auto; margin:1px auto;" class="betterCheck"></td>
													<td width="8"> </td>
												  	
													<td width="462"><p style="font-size: 14px; color: #221f20; line-height: 19px; font-weight: 400; font-family: 'Roboto', sans-serif; margin: 0; text-align: left; ">Earned certification in Shielded Metal Arc Welding and Gas Tungsten Arc 
Welding from the American Welding Society (AWS).</p></td>
                                                      
													<td width="32"> </td>
                                                     
                                                    </tr>
													  
                                                    <tr valign="top">
												  		<td colspan="5" height="12"></td>
                                                    </tr>
													  
													  
                                                    <tr valign="top">
												  	<td width="20"> </td>
													<td width="18" valign="top"><img src="https://ss-usa.s3.amazonaws.com/companies/MzQ0MAIA/uploads/634dbef259a43/checkmark.png" width="18" height="18" alt="" style="display:block;max-width:100%;height:auto; margin:1px auto;" class="betterCheck"></td>
													<td width="8"> </td>
												  	
													<td width="462" valign="top"><p style="font-size: 14px; color: #221f20; line-height: 19px; font-weight: 400; font-family: 'Roboto', sans-serif; margin: 0; text-align: left; ">Completed job training in just <span style="font-weight:700;">3 months!</span></p></td>
                                                      
													<td width="32"> </td>
                                                     
                                                    </tr>
													  
                                                    <tr valign="top">
												  		<td colspan="5" height="12"></td>
                                                    </tr>
													  
													  
                                                    <tr valign="top">
												  	<td width="20"> </td>
													<td width="18" valign="top"><img src="https://ss-usa.s3.amazonaws.com/companies/MzQ0MAIA/uploads/634dbef259a43/checkmark.png" width="18" height="18" alt="" style="display:block;max-width:100%;height:auto; margin:1px auto;" class="betterCheck"></td>
													<td width="8"> </td>
												  	
													<td width="462" valign="top"><p style="font-size: 14px; color: #221f20; line-height: 19px; font-weight: 400; font-family: 'Roboto', sans-serif; margin: 0; text-align: left; "><span style="font-weight:700;">Hired by Huntington Ingalls Industries immediately</span> after completing 
training and upon discharge from the US Air Force this past September.</p></td>
                                                      
													<td width="32"> </td>
                                                     
                                                    </tr>
                                                  </tbody>
                                                </table>
                                              </th>
                                            </tr>
											     <tr>
                                              <th height="32"></th>
                                            </tr>
											  
											  
											</tbody>
										  </table>
										</th>
									  </tr>
									</tbody>
								  </table>
								  
								</th>
							  </tr>
							  
							  
							   <tr>
                                              <th height="27" colspan="5" class="hideMobile"> </th>
                                            </tr> 
							  
									     <tr>
                              <th align="left">
                                <table width="542" border="0" cellspacing="0" cellpadding="0">
                                  <tbody>
                                    <tr>                                                     
                                      <th width="542" class="">
                                        <table border="0" cellspacing="0" cellpadding="0">
                                          <tbody>  
										  
										  
											  
                                            <tr class="collapse-mobile">
                                              <td class="">
												
												
												<table width="542" border="0" cellpadding="0" cellspacing="0" align="center" style="width: 542px; background: #c7312e;" background="#c7312e">
                                                  <tbody>
<tr>
<th height="26"></th>
</tr>
                                                    <tr>
                                              <th>
                                                <table width="540" border="0" cellpadding="0" cellspacing="0" align="center" style="width: 540px;">
                                                  <tbody>
                                                    <tr valign="top">
														
														<td width="20" class="hideMobile"></td>
                                                      <td width="424"> 														
<p style="text-align: center; margin: 0;" class="spaceItBetter"><img src="https://ss-usa.s3.amazonaws.com/companies/MzQ0MAIA/uploads/634dbef259a43/signup.png" width="424" height="68" alt="Sign up with no im[pact to your G.I. Bill benefits" style="display:block;max-width:100%;height:auto; margin: 0 auto;" class=""></p></td>
                                                      
                                                      
														<td width="96" class="hideMobile"></td>
                                                     
                                                    </tr>
                                                  </tbody>
                                                </table>
                                              </th>
                                            </tr>
<tr>
<th height="26"></th>
</tr>
								<tr>
                                              <th>
                                                <table width="540" border="0" cellpadding="0" cellspacing="0" align="center" style="width: 540px;">
                                                  <tbody>
                                                    <tr valign="top">
														
														<td width="20" class="hideMobile"></td>
                                                      <td width="480"> 														
<p style="font-size: 14px; color: #fff; line-height: 1.3; font-weight: 400; font-family: 'Roboto', Arial, sans-serif; margin: 0; text-align: left;" class="spaceItBetter centerMobile">Operation Next is a DoD-sponsored, SkillBridge-approved training program 
offered free of charge to eligible service members. <span style="font-weight: 700;">Enrolling will not affect your G.I. bill education benefits.</span></p></td>
                                                      
                                                      
														<td width="40" class="hideMobile"></td>
                                                     
                                                    </tr>
                                                  </tbody>
                                                </table>
                                              </th>
                                            </tr>					  
                                                    
<tr>
<th height="20" class="hideMobile"></th>
</tr>
			<tr>
                                              <th>
                                                <table width="540" border="0" cellpadding="0" cellspacing="0" align="center" style="width: 540px;">
                                                  <tbody>
                                                    <tr valign="top">
														
														<td width="16" class="hideMobile"></td>
                                                      <td width="508" style="border-bottom:1px solid #fff;"></td>
                                                      
                                                      
														<td width="16" class="hideMobile"></td>
                                                     
                                                    </tr>
                                                  </tbody>
                                                </table>
                                              </th>
                                            </tr>	
													                                                    
<tr>
<th height="20"></th>
</tr>
      									    <tr>
                                              <th>
                                                <table width="540" border="0" cellpadding="0" cellspacing="0" align="center" style="width: 540px;">
                                                  <tbody>
                                                    <tr valign="top">
														
														<td width="25" class="hideMobile"></td>
                                                      <td width="490"> 														
<p style="font-size: 16px; color: #d4d4ce; line-height: 1.3; font-weight: 700; font-family: 'Roboto', Arial, sans-serif; margin: 0; text-align: left;" class="spaceItBetter centerMobile">Visit OpNextJobs.com and choose from popular training such as:</p></td>
                                                      
                                                      
														<td width="25" class="hideMobile"></td>
                                                     
                                                    </tr>
                                                  </tbody>
                                                </table>
                                              </th>
                                            </tr>	                                        
<tr>
<th height="10" class="hideMobile"></th>
</tr>

				    <tr>
                                              <th>
                                                <table width="540" border="0" cellpadding="0" cellspacing="0" align="center" style="width: 540px;">
                                                  <tbody>
                                                    <tr valign="top">
														
														<td width="30"></td>
                                                      <td width="288"> 														
<p style="font-size: 11px; color: #fff; line-height: 1.3; font-weight: 700; font-family: 'Roboto', Arial, sans-serif; margin: 0 0 4px; text-align: left;" class="spaceItBetter centerMobile">Computer Numeric Control Machining (CNC)</p>								
<p style="font-size: 11px; color: #fff; line-height: 1.3; font-weight: 700; font-family: 'Roboto', Arial, sans-serif; margin: 0 0 4px; text-align: left;" class="spaceItBetter centerMobile">Welding</p>								
<p style="font-size: 11px; color: #fff; line-height: 1.3; font-weight: 700; font-family: 'Roboto', Arial, sans-serif; margin: 0 0 4px; text-align: left;" class="spaceItBetter centerMobile">Industrial Technology Maintenance</p>								
<p style="font-size: 11px; color: #fff; line-height: 1.3; font-weight: 700; font-family: 'Roboto', Arial, sans-serif; margin: 0; text-align: left;" class="spaceItBetter centerMobile">Robotics Technician</p></td>
														
<td width="157"><p style="text-align: center; margin: 15px 0 0;"><a href="https://www.opnextjobs.com/enroll/" target="_blank"><img src="https://ss-usa.s3.amazonaws.com/companies/MzQ0MAIA/uploads/634dbef259a43/learnmore.png" width="157" height="34" alt="Learn More" style="display:block;max-width:100%;height:auto; margin: 0 auto;" class=""></a></p></td>
                                                      
														<td width="65"></td>
                                                     
                                                    </tr>
                                                  </tbody>
                                                </table>
                                              </th>
                                            </tr>	
                                                    <tr>
<th height="20" class="hideMobile"></th>
</tr>
                                                    
                                                  </tbody>
                                                </table>
												
												</td>
</tr>
                                            <tr>
                                              <th height="10" class="hideMobile"></th>
                                            </tr>
                                            <tr>
                                              <th height="17" class=""></th>
                                            </tr>
                                            <tr>
												
												 <td>
												
												
												<table width="542" border="0" cellpadding="0" cellspacing="0" align="center" style="width: 542px;">
                                                  <tbody>
                                                    <tr valign="top" class="-mobile">
                                                      <td width="30" height="15" class="hideMobile"></td>
                                                     
														
                                                      <td width="240">
														
<p style="font-size: 18px; color: #000; line-height: 1; font-weight: 700; font-family: 'Oswald', sans-serif; margin: 0 0 7px; text-align: left;" class="spaceItBetter centerMobile">Questions?</p>
<p style="font-size: 16px; color: #273c8c; line-height: 1; font-weight: 700; font-family: 'Oswald', sans-serif; margin: 0 0 11px; text-align: left;" class="spaceItBetter centerMobile"><span style="font-weight:500; color:#000;">Contact</span> Operation Next:</p>

														  
														  
														  
									<table width="100%" border="0" cellpadding="0" cellspacing="0" align="center" class="phoneEmailTable">
                                                  <tbody>
                                                    <tr valign="top">
                                                      <td width="24" height="24" valign="middle">
<img src="https://ss-usa.s3.amazonaws.com/companies/MzQ0MAIA/uploads/634dbef259a43/icon-phone.png" width="24" height="24" alt="data" style="display:block;max-width:100%;height:auto;" class="">
														</td>
														<td width="9" class="">&nbsp;</td>
														<td width="200" height="24" valign="middle">
<p style="font-size: 13px; color: #273c8c; line-height: 1.1; font-weight: bold; font-family: 'Roboto Slab', serif; margin: 0; text-align: left;" class=""><a href="mailto:3133552478" style="text-decoration: none; color:#273c8c;">(313) 355-2478</a></p>
														</td>
													  </tr>
                                                    <tr valign="top">
                                                      <td height="5" valign="middle">
														</td>
													  </tr>
                                                    <tr valign="top">
                                                      <td width="24" height="24" valign="middle">
<img src="https://ss-usa.s3.amazonaws.com/companies/MzQ0MAIA/uploads/634dbef259a43/icon-email.png" width="24" height="24" alt="data" style="display:block;max-width:100%;height:auto;" class="">
														</td>
														<td width="9" class="">&nbsp;</td>
														<td width="200" height="24" valign="middle">
<p style="font-size: 13px; color: #273c8c; line-height: 1.1; font-weight: bold; font-family: 'Roboto Slab', serif; margin: 0; text-align: left;" class=""><a href="mailto:communications@lift.technology" style="text-decoration: none; color:#273c8c;">communications@lift.technology</a></p>
														</td>
													  </tr>
													  </tbody>
														  </table>					  
														  
													 
														
													</td>
                                                      <td width="21" class="hideMobile">&nbsp;</td>
														
                                                      
														
                                                      <td width="251" valign="top" class="hideMobile">
													 <img src="https://ss-usa.s3.amazonaws.com/companies/MzQ0MAIA/uploads/634dbef259a43/soldier-learning.png" width="251" height="139" alt="Learning" style="display:block;max-width:100%;height:auto;" class="">
														</td>
														
                                                    </tr>
                                                    
                                                    
                                                    
                                                    
                                                    
                                                    
                                                  </tbody>
                                                </table>
												
												</td>
                                               </tr>
											   <tr class="collapse-mobile">
                                                                <td height="25" width="542" style="border-bottom: 2px solid #273c8c;" colspan="5"></td>
                                                                
                                                                
                                                               
                                                              </tr>
											  
                                            <tr>
                                              <th height="20" class=""></th>
                                            </tr>	
											  
											  <tr>
												
												 <td>
												
												 <table width="542" border="0" cellpadding="0" cellspacing="0" align="center" style="width: 542px;">
                                                  <tbody>
                                                    <tr valign="top" class="">
                                                      <td width="21">&nbsp;</td>
                                                     
                                                      <td width="500">
<p style="font-size: 18px; color: #636466; line-height: 1.5; font-weight: 700; font-family: 'Oswald', sans-serif; margin: 0; text-align: center;" class="spaceItBetter centerMobile">Are you within 6 months of separation? Sign up now!</p>			
<p style="font-size: 16px; color: #636466; line-height: 1.5; font-weight: 500; font-family: 'Oswald', sans-serif; margin: 0 0 15px; text-align: center;" class="spaceItBetter centerMobile">Operation Next is open to all active-duty military and National Guard and 
Reserve service members and their spouses. So, enroll today and boost your 
skills <span style="font-weight:700;">before you’re discharged.</span> </p></td>
														
														
                                                      
          <td width="21">&nbsp;</td>
													  </tr></tbody>
														  </table>
													 
				
													 
												  </td>
											  </tr>
											  <tr>
											  <td>

														  
										  <table width="542" border="0" cellpadding="0" cellspacing="0" align="center" style="width: 542px;">
                                                  <tbody>
                                                    <tr valign="top" class="">
											  <td width="190" class="hideMobile">&nbsp;</td>
                                                     
                                                  <td width="162">
														
														
														
						  <table border="0" cellpadding="0" cellspacing="0" align="center" class="keepWidth">
                                                  <tbody>
                                                    <tr valign="top" class="">
														
														    <td width="132">
<p style="text-align: right; margin: 0;">
	<a href="https://www.opnextjobs.com/enroll/" target="_blank" style="font-family: 'Roboto Slab', serif; font-weight: 700; text-decoration: none; color: #273c8c; font-size:14px; line-height: 24px;">START LEARNING</a>
</p></td>
														
														
                                                      <td width="6">&nbsp;</td>
														<td width="24" valign="middle"> <a href="https://www.opnextjobs.com/enroll/" target="_blank"><img src="https://ss-usa.s3.amazonaws.com/companies/MzQ0MAIA/uploads/634dbef259a43/icon-arrow.png" width="24" height="24" alt="Learning" style="display:block;max-width:100%;height:auto;" class=""></a></td>
													  </tr>
															  </tbody>
													  </table>
														
														
														
														
														
														</td>
          <td width="190" class="hideMobile">&nbsp;</td>
													  </tr></tbody>
														  </table>
														  
														  
														  
												
												
												</td>
                                               </tr>
											   
                                          </tbody>
                                        </table>
                                      </th>
										
										
										
										 <th width="16" class="hideMobile"></th>
                                    </tr>
                                  </tbody>
                                </table>
                              </th>
                            </tr>
							  
							   <tr>
                                              <th height="20" colspan="5" class=""> </th>
                                            </tr>  
                          </tbody>
                        </table>
                      </th>
                    </tr>
                  </tbody>
                </table>
              </th>
            </tr>
          </tbody>
        </table>
				
				  
	  <table width="542" border="0" cellpadding="0" cellspacing="0" align="center" style="width: 542px; background: #273c8c; border-collapse: collapse; mso-table-lspace: 0pt; mso-table-rspace: 0pt;" background="#e6e7e8">
                                                  <tbody>
													  
                                            <tr><td>
				  
				  
				  <table border="0" cellpadding="0" cellspacing="0" align="center" style="border-collapse: collapse; mso-table-lspace: 0pt; mso-table-rspace: 0pt;">
                                                  <tbody>
													  
                                            <tr>
                                              <th colspan="3" height="20" class=""></th>
                                            </tr>
                                                    <tr valign="top" class="">
                                                      <td width="30"></td>
                                                     
														
                                                      <td width="482" class="spaceItBetter">
														
<p style="font-size: 12px; color: #fff; line-height:15px; font-weight: 700; font-family: 'Roboto', Arial, sans-serif; margin: 0 0 10px; text-align: left;" class="spaceItBetter centerMobile">Operation Next brings companies and talent together by preparing separating service members with the skills needed to thrive in an advanced manufacturing career.</p>

<p style="font-size: 11px; color: #fff; line-height:15px; font-weight: 700; font-family: 'Roboto', Arial, sans-serif; margin: 0 0 10px; text-align: center;" class="spaceItBetter centerMobile">These companies are among those that have hired Operation Next graduates.</p>
														  
														  <img src="https://ss-usa.s3.amazonaws.com/companies/MzQ0MAIA/uploads/634dbef259a43/companies.png" width="415" height="100" alt="Companies" style="display:block;max-width:100%;height:auto;margin:0 auto;" class="">	
													</td>
                                                
														
                                                     
														
                                                      <td width="30"></td>
                                                    </tr>
													  
													          
													  
													 
                                                    
                                                    
                                                    
                                                    <tr>
                                              <th height="10" class=""></th>
                                            </tr>
													     
													  
													 
													  
													  <tr>
                                              <th height="15" colspan="3" class=""> </th>
                                            </tr>  
													 
                                                    
                                                    
                                                  </tbody>
                                                </table>
				  
				  
				  
												</td>
													  </tr>
		  </tbody>
				  </table>
				  
				  
				  <table width="542" border="0" cellpadding="0" cellspacing="0" align="center" style="width: 542px; background: #fff; border-collapse: collapse; mso-table-lspace: 0pt; mso-table-rspace: 0pt;" background="#e6e7e8">
                                                  <tbody>
													  
                                            <tr><td>
				  
				  
				  <table border="0" cellpadding="0" cellspacing="0" align="center" style="border-collapse: collapse; mso-table-lspace: 0pt; mso-table-rspace: 0pt;">
                                                  <tbody>
													  
                                            <tr>
                                              <th colspan="7" height="7" class="hideMobile"></th>
                                            </tr>
                                                    <tr valign="top" class="collapse-mobile">
														
														
														<td width="17"></td>
                                                      <td width="76" valign="middle" class="">
														
													<img src="https://ss-usa.s3.amazonaws.com/companies/MzQ0MAIA/uploads/634dbef259a43/dod-logo.png" width="76" height="60" alt="data" style="display:block;max-width:100%;height:auto;" class="centerMobileIMG">			
														
														
														</td>
														<td width="121" class="hideMobile">&nbsp;</td>
                                                     
														
                                                      <td width="109" valign="middle">
											 
					<img src="https://ss-usa.s3.amazonaws.com/companies/MzQ0MAIA/uploads/634dbef259a43/lift-logo-footer.png" width="109" height="64" alt="Operation Next" style="display:block;max-width:100%;height:auto;margin-top:17px;" class="centerMobileIMG">									
													</td>
                                                
														
                                                     
														
                                                      <td width="112"></td>
														
														
                                                      <td width="87" valign="middle">
														
														  <table border="0" cellpadding="0" cellspacing="0" align="center" style="border-collapse: collapse; mso-table-lspace: 0pt; mso-table-rspace: 0pt;" class="socialsFooter">
                                                  <tbody>
													  
                                            <tr>
                                              <th width="19" style="padding-right: 12px;">
													<a href="https://www.facebook.com/opnextjobs/" target="_blank"><img src="https://ss-usa.s3.amazonaws.com/companies/MzQ0MAIA/uploads/634dbef259a43/icon-fb.png" width="19" height="19" alt="Operation Next" style="display:block;max-width:100%;height:auto;" class=""></a>
												</th>
                                              <th width="25" style="padding-right: 11px;">
													<a href="https://www.linkedin.com/company/operation-next/" target="_blank"><img src="https://ss-usa.s3.amazonaws.com/companies/MzQ0MAIA/uploads/634dbef259a43/icon-linkedin.png" width="25" height="19" alt="Operation Next" style="display:block;max-width:100%;height:auto;" class="">	</a>	
												</th>
                                              <th width="20">
												 <a href="https://twitter.com/opnextjobs" target="_blank"> <img src="https://ss-usa.s3.amazonaws.com/companies/MzQ0MAIA/uploads/634dbef259a43/icon-twitter.png" width="20" height="19" alt="Operation Next" style="display:block;max-width:100%;height:auto;" class="">	</a>	
												</th>
                                            </tr>
															  </tbody>
														  </table>
														
														</td>
														
														
                                                      <td width="20"></td>
                                                    </tr>
                                                    
                                                    
                                                    
                                                    <tr>
                                              <th height="10" class="hideMobile"></th>
                                            </tr>
													     
													  
													 
													  
													 
													 
                                                    
                                                    
                                                  </tbody>
                                                </table>
				  
				  
				  
												</td>
													  </tr>
													  
													  <tr> <td colspan="7">
														  
														  
														  <p style="font-size: 10px; color: #000; line-height: 1.4; font-weight: 400; font-family: 'Roboto', Arial, sans-serif; margin: 0 0 20px; text-align: center;" class="spaceItBetter centerMobile">Operation Next is Powered by LIFT. Learn more at www.lift.technology.<br>
Copyright © 2022  All Rights Reserved<br>
															  Operated by the American Lightweight Materials Manufacturing Innovation Institute (ALMMII)</p></td></tr>
		  </tbody>
				  </table>
				  
        
				</th>
				
			<th width="29" class="hideMobile">&nbsp;</th>
			  </tr>
		  </tbody>
	  </table></body><grammarly-desktop-integration data-grammarly-shadow-root="true"></grammarly-desktop-integration></html>